[pytest]
# Import tests within the fileformats.extras namespace package by their full module
# name, so the extras aren't imported a second time as a top-level package
consider_namespace_packages = true
#log_cli=true
#log_level=NOTSET
filterwarnings =
    default::DeprecationWarning:__main__
    ignore::DeprecationWarning
    ignore::_pytest.warning_types.PytestCollectionWarning
    ignore::PendingDeprecationWarning
